name: 'Verify Development'

on:
  pull_request:
    branches: [ 'development' ]

env:
  GODOT_VERSION: 4.3
  VERSION_FILE: project.godot
  VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Extract old version string
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.VERSION_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version-old

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Extract new version string
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.VERSION_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version-new

      - name: Check semantic version bump
        uses: CapsCollective/version-actions/check-version-bump@v1.0
        with:
          new-version: ${{ steps.extract-version-new.outputs.version-string }}
          old-version: ${{ steps.extract-version-old.outputs.version-string }}
      
  # run-project-validation:
  #   needs: check-version-bump
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout current branch
  #       uses: actions/checkout@v4

  #     - name: Install Godot
  #       uses: CapsCollective/godot-actions/install-godot@v1.0
  #       with:
  #         godot-version: ${{ env.GODOT_VERSION }}
  #       id: install-godot

  #     - name: Open Godot editor for reimport
  #       run: ${{ steps.install-godot.outputs.godot-executable }} --import --headless --verbose

  #     - name: Run project validations
  #       run: ${{ steps.install-godot.outputs.godot-executable }} --script scripts/run_validations.gd --headless

  build:
    # needs: run-project-validation
    needs: check-version-bump
    runs-on: macos-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Install Godot
        uses: CapsCollective/godot-actions/install-godot@v1.0
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Open Godot editor for reimport
        run: ${{ steps.install-godot.outputs.godot-executable }} --import --headless --verbose

      - name: Apply version to export information
        run: ${{ steps.install-godot.outputs.godot-executable }} --script scripts/apply_version.gd --headless

      - name: Build and upload artifacts for all platforms
        uses: CapsCollective/godot-actions/build-godot@v1.2
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
